import sys

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets

import Tab_UI.tab1
import UI_py.New_Build
dbname = './database.db'  # 存储预设的数据库名字
presetTableName = 'commandPreset'  # 存储预设的表单名字
preferenceTableName = 'preference'
styleFile = './style.css'  # 样式表的路径
finalCommand = ''
version = 'V1.0'

class MainWindow(QMainWindow):
	def __init__(self):
		super().__init__()
		self._update_checker = None
		self.initGui()
		self.status = self.statusBar()

	def initGui(self):
		# 定义中心控件为多 tab 页面
		self.tabs = QTabWidget()
		self.setCentralWidget(self.tabs)

		self.setObjectName("MainWindow")
		self.resize(900, 720)
		self.setMinimumSize(QtCore.QSize(900, 720))
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(9)
		self.setFont(font)
		self.tabs.setGeometry(QtCore.QRect(0, 0, 1011, 771))
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(12)
		self.tabs.setFont(font)
		self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.tabs.setObjectName("tabWidget")

		# 定义多个不同功能的 tab
		self.HomeTab = HomeTab()
		self.ProductTrackTab = ProductTrackTab()
		self.PlatformSelectionTab = PlatformSelectionTab()
		self.KOL_InitialSelectionTab = KOL_InitialSelectionTab()
		self.KOL_CompareTab = KOL_CompareTab()
		self.KOL_ForecastTab = KOL_ForecastTab()
		self.FinalProposalTab = FinalProposalTab()

		# 将不同功能的 tab 添加到主 tabWidget
		self.tabs.addTab(self.HomeTab, self.tr('主页'))
		self.tabs.addTab(self.ProductTrackTab, self.tr('产品赛道'))
		self.tabs.addTab(self.PlatformSelectionTab, self.tr('平台选择'))
		self.tabs.addTab(self.KOL_InitialSelectionTab, self.tr('KOL初筛'))
		self.tabs.addTab(self.KOL_CompareTab, self.tr('KOL选择'))
		self.tabs.addTab(self.KOL_ForecastTab, self.tr('发展预测'))
		self.tabs.addTab(self.FinalProposalTab, self.tr('最终推荐方案'))



		self.adjustSize()
		self.show()

	def onUpdateText(self, text):
		"""Write console output to text widget."""

		cursor = self.consoleTab.consoleEditBox.textCursor()
		cursor.movePosition(QTextCursor.End)
		cursor.insertText(text)
		self.consoleTab.consoleEditBox.setTextCursor(cursor)
		self.consoleTab.consoleEditBox.ensureCursorVisible()

	def closeEvent(self, event):
		"""Shuts down application on close."""
		# Return stdout to defaults.
		if MainWindow.ConfigTab.hideToSystemTraySwitch.isChecked():
			event.ignore()
			self.hide()
		else:
			sys.stdout = sys.__stdout__
			super().closeEvent(event)


############# 不同功能的 Tab ################

class HomeTab(QWidget):
	def __init__(self):
		super().__init__()
		self.initGui()

	def initGui(self):
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(12)
		self.setFont(font)
		self.setObjectName("HomeTab")
		self.gridLayoutWidget = QtWidgets.QWidget(self)
		self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 571))
		self.gridLayoutWidget.setObjectName("gridLayoutWidget")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
		self.gridLayout_2.setContentsMargins(20, 8, 10, 8)
		self.gridLayout_2.setHorizontalSpacing(20)
		self.gridLayout_2.setVerticalSpacing(8)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.New_Build_button = QtWidgets.QPushButton(self.gridLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.New_Build_button.sizePolicy().hasHeightForWidth())
		self.New_Build_button.setSizePolicy(sizePolicy)
		self.New_Build_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.New_Build_button.setObjectName("New_Build_button")
		self.gridLayout_2.addWidget(self.New_Build_button, 0, 0, 1, 1)
		self.splitter = QtWidgets.QSplitter(self.gridLayoutWidget)
		self.splitter.setOrientation(QtCore.Qt.Vertical)
		self.splitter.setObjectName("splitter")
		self.label_2 = QtWidgets.QLabel(self.splitter)
		self.label_2.setAlignment(QtCore.Qt.AlignCenter)
		self.label_2.setObjectName("label_2")
		self.listView = QtWidgets.QListView(self.splitter)
		self.listView.setObjectName("listView")
		self.gridLayout_2.addWidget(self.splitter, 0, 1, 1, 1)
		self.line = QtWidgets.QFrame(self.gridLayoutWidget)
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)

		self.New_Build_button.setText( "新建咨询")
		self.label_2.setText( "历史记录")


class ProductTrackTab(QWidget):
	def __init__(self):
		super().__init__()
		self.initGui()

	def initGui(self):
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(10)
		self.setFont(font)
		self.setObjectName("tab_2")
		self.layoutWidget = QtWidgets.QWidget(self)
		self.layoutWidget.setGeometry(QtCore.QRect(480, 0, 481, 331))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout_2.setContentsMargins(0, 12, 0, 0)
		self.verticalLayout_2.setSpacing(12)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.label_11 = QtWidgets.QLabel(self.layoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
		self.label_11.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(12)
		self.label_11.setFont(font)
		self.label_11.setObjectName("label_11")
		self.verticalLayout_2.addWidget(self.label_11)
		self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
		self.graphicsView.setObjectName("graphicsView")
		self.verticalLayout_2.addWidget(self.graphicsView)
		self.layoutWidget_2 = QtWidgets.QWidget(self)
		self.layoutWidget_2.setGeometry(QtCore.QRect(480, 350, 481, 331))
		self.layoutWidget_2.setObjectName("layoutWidget_2")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
		self.verticalLayout_3.setContentsMargins(0, 12, 0, 0)
		self.verticalLayout_3.setSpacing(12)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(12)
		self.label_12.setFont(font)
		self.label_12.setObjectName("label_12")
		self.verticalLayout_3.addWidget(self.label_12)
		self.listView_2 = QtWidgets.QListView(self.layoutWidget_2)
		self.listView_2.setObjectName("listView_2")
		self.verticalLayout_3.addWidget(self.listView_2)
		self.layoutWidget_3 = QtWidgets.QWidget(self)
		self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 456, 591))
		self.layoutWidget_3.setObjectName("layoutWidget_3")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
		self.verticalLayout.setContentsMargins(8, 12, 8, 12)
		self.verticalLayout.setObjectName("verticalLayout")
		self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
		self.label_7.setSizePolicy(sizePolicy)
		self.label_7.setTextFormat(QtCore.Qt.AutoText)
		self.label_7.setAlignment(QtCore.Qt.AlignCenter)
		self.label_7.setWordWrap(False)
		self.label_7.setObjectName("label_7")
		self.verticalLayout.addWidget(self.label_7)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setContentsMargins(8, -1, 24, -1)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
		self.label_8.setSizePolicy(sizePolicy)
		self.label_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_8.setObjectName("label_8")
		self.horizontalLayout_2.addWidget(self.label_8)
		self.comboBox = QtWidgets.QComboBox(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
		self.comboBox.setSizePolicy(sizePolicy)
		self.comboBox.setObjectName("comboBox")
		self.horizontalLayout_2.addWidget(self.comboBox)
		self.toolButton = QtWidgets.QToolButton(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
		self.toolButton.setSizePolicy(sizePolicy)
		self.toolButton.setObjectName("toolButton")
		self.horizontalLayout_2.addWidget(self.toolButton)
		self.verticalLayout.addLayout(self.horizontalLayout_2)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setContentsMargins(0, -1, 36, -1)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
		self.label_9.setSizePolicy(sizePolicy)
		self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_9.setObjectName("label_9")
		self.horizontalLayout_3.addWidget(self.label_9)
		self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
		self.comboBox_2.setSizePolicy(sizePolicy)
		self.comboBox_2.setObjectName("comboBox_2")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.comboBox_2.addItem("")
		self.horizontalLayout_3.addWidget(self.comboBox_2)
		self.verticalLayout.addLayout(self.horizontalLayout_3)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setContentsMargins(0, -1, 36, -1)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
		self.label_10.setSizePolicy(sizePolicy)
		self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_10.setObjectName("label_10")
		self.horizontalLayout_4.addWidget(self.label_10)
		self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_3)
		self.comboBox_3.setObjectName("comboBox_3")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.comboBox_3.addItem("")
		self.horizontalLayout_4.addWidget(self.comboBox_3)
		self.verticalLayout.addLayout(self.horizontalLayout_4)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setContentsMargins(8, 12, 8, 12)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.pushButton = QtWidgets.QPushButton(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
		self.pushButton.setSizePolicy(sizePolicy)
		self.pushButton.setObjectName("pushButton")
		self.horizontalLayout_5.addWidget(self.pushButton)
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem)
		self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
		self.pushButton_2.setSizePolicy(sizePolicy)
		self.pushButton_2.setObjectName("pushButton_2")
		self.horizontalLayout_5.addWidget(self.pushButton_2)
		self.verticalLayout.addLayout(self.horizontalLayout_5)
		self.line_2 = QtWidgets.QFrame(self)
		self.line_2.setGeometry(QtCore.QRect(450, 0, 20, 591))
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")

		self.label_11.setText("产品词云图")
		self.label_12.setText("推荐的KOL分组")
		self.label_7.setText("提示：文件中需要包含产品的初始宣传、介绍文案")
		self.label_8.setText("点击上传文件")
		self.toolButton.setText("...")
		self.label_9.setText("产品定位：")
		self.comboBox_2.setItemText(0, "电子")
		self.comboBox_2.setItemText(1, "母婴")
		self.comboBox_2.setItemText(2, "服饰")
		self.comboBox_2.setItemText(3, "日用品")
		self.comboBox_2.setItemText(4, "美妆")
		self.label_10.setText("产品细分：")
		self.comboBox_3.setItemText(0, "护肤")
		self.comboBox_3.setItemText(1, "修复")
		self.comboBox_3.setItemText(2, "彩妆")
		self.comboBox_3.setItemText(3, "洗护")
		self.comboBox_3.setItemText(4, "防晒")
		self.pushButton.setText("确定")
		self.pushButton_2.setText("下一步")

class PlatformSelectionTab(QWidget):
	def __init__(self):
		super().__init__()
		self.initGui()

	def initGui(self):
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(10)
		self.setFont(font)
		self.setObjectName("tab_3")
		self.pushButton_10 = QtWidgets.QPushButton(self)
		self.pushButton_10.setGeometry(QtCore.QRect(140, 510, 93, 41))
		self.pushButton_10.setObjectName("pushButton_10")
		self.pushButton_11 = QtWidgets.QPushButton(self)
		self.pushButton_11.setGeometry(QtCore.QRect(490, 510, 93, 41))
		self.pushButton_11.setObjectName("pushButton_11")
		self.label_4 = QtWidgets.QLabel(self)
		self.label_4.setGeometry(QtCore.QRect(0, 20, 241, 71))
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(14)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.layoutWidget_4 = QtWidgets.QWidget(self)
		self.layoutWidget_4.setGeometry(QtCore.QRect(0, 140, 949, 122))
		self.layoutWidget_4.setObjectName("layoutWidget_4")
		self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
		self.gridLayout.setContentsMargins(2, 4, 2, 4)
		self.gridLayout.setObjectName("gridLayout")
		self.label_13 = QtWidgets.QLabel(self.layoutWidget_4)
		self.label_13.setAlignment(QtCore.Qt.AlignCenter)
		self.label_13.setObjectName("label_13")
		self.gridLayout.addWidget(self.label_13, 1, 4, 1, 1)
		self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
		self.doubleSpinBox_3.setMaximum(100.0)
		self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
		self.gridLayout.addWidget(self.doubleSpinBox_3, 2, 2, 1, 1)
		self.label_14 = QtWidgets.QLabel(self.layoutWidget_4)
		self.label_14.setAlignment(QtCore.Qt.AlignCenter)
		self.label_14.setObjectName("label_14")
		self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)
		self.label_5 = QtWidgets.QLabel(self.layoutWidget_4)
		self.label_5.setAlignment(QtCore.Qt.AlignCenter)
		self.label_5.setObjectName("label_5")
		self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
		self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
		self.doubleSpinBox_5.setMaximum(100.0)
		self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
		self.gridLayout.addWidget(self.doubleSpinBox_5, 2, 4, 1, 1)
		self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
		self.doubleSpinBox_2.setMaximum(100.0)
		self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
		self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 1, 1, 1)
		self.label_6 = QtWidgets.QLabel(self.layoutWidget_4)
		self.label_6.setAlignment(QtCore.Qt.AlignCenter)
		self.label_6.setObjectName("label_6")
		self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
		self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
		self.doubleSpinBox_4.setMaximum(100.0)
		self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
		self.gridLayout.addWidget(self.doubleSpinBox_4, 2, 3, 1, 1)
		self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
		self.doubleSpinBox.setMaximum(100.0)
		self.doubleSpinBox.setObjectName("doubleSpinBox")
		self.gridLayout.addWidget(self.doubleSpinBox, 2, 0, 1, 1)
		self.label_15 = QtWidgets.QLabel(self.layoutWidget_4)
		self.label_15.setAlignment(QtCore.Qt.AlignCenter)
		self.label_15.setObjectName("label_15")
		self.gridLayout.addWidget(self.label_15, 1, 3, 1, 1)
		self.checkBox = QtWidgets.QCheckBox(self.layoutWidget_4)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
		self.checkBox.setSizePolicy(sizePolicy)
		self.checkBox.setObjectName("checkBox")
		self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
		self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget_4)
		self.checkBox_2.setObjectName("checkBox_2")
		self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
		self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget_4)
		self.checkBox_4.setObjectName("checkBox_4")
		self.gridLayout.addWidget(self.checkBox_4, 0, 2, 1, 1)
		self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget_4)
		self.checkBox_3.setObjectName("checkBox_3")
		self.gridLayout.addWidget(self.checkBox_3, 0, 3, 1, 1)
		self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget_4)
		self.checkBox_5.setObjectName("checkBox_5")
		self.gridLayout.addWidget(self.checkBox_5, 0, 4, 1, 1)
		self.label_18 = QtWidgets.QLabel(self)
		self.label_18.setGeometry(QtCore.QRect(170, 0, 391, 31))
		self.label_18.setObjectName("label_18")
		self.layoutWidget_5 = QtWidgets.QWidget(self)
		self.layoutWidget_5.setGeometry(QtCore.QRect(0, 350, 771, 101))
		self.layoutWidget_5.setObjectName("layoutWidget_5")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_5)
		self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_5)
		self.pushButton_8.setObjectName("pushButton_8")
		self.gridLayout_3.addWidget(self.pushButton_8, 1, 1, 1, 1)
		self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget_5)
		self.pushButton_9.setObjectName("pushButton_9")
		self.gridLayout_3.addWidget(self.pushButton_9, 0, 1, 1, 1)
		self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_5)
		self.pushButton_7.setObjectName("pushButton_7")
		self.gridLayout_3.addWidget(self.pushButton_7, 1, 0, 1, 1)
		self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_5)
		self.pushButton_6.setObjectName("pushButton_6")
		self.gridLayout_3.addWidget(self.pushButton_6, 0, 0, 1, 1)
		self.label_20 = QtWidgets.QLabel(self)
		self.label_20.setGeometry(QtCore.QRect(0, 260, 641, 31))
		self.label_20.setObjectName("label_20")
		self.label_17 = QtWidgets.QLabel(self)
		self.label_17.setGeometry(QtCore.QRect(0, 90, 91, 41))
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.label_17.setFont(font)
		self.label_17.setStyleSheet("background: rgb(198, 198, 198);")
		self.label_17.setObjectName("label_17")
		self.label_16 = QtWidgets.QLabel(self)
		self.label_16.setGeometry(QtCore.QRect(90, 470, 641, 31))
		self.label_16.setObjectName("label_16")
		self.label_19 = QtWidgets.QLabel(self)
		self.label_19.setGeometry(QtCore.QRect(0, 300, 91, 41))
		font = QtGui.QFont()
		font.setFamily("微软雅黑")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.label_19.setFont(font)
		self.label_19.setStyleSheet("background: rgb(198, 198, 198);")
		self.label_19.setObjectName("label_19")
		self.graphicsView_2 = QtWidgets.QGraphicsView(self)
		self.graphicsView_2.setGeometry(QtCore.QRect(10, 560, 771, 131))
		self.graphicsView_2.setObjectName("graphicsView_2")
		self.label_3 = QtWidgets.QLabel(self)
		self.label_3.setGeometry(QtCore.QRect(0, 0, 161, 31))
		font = QtGui.QFont()
		font.setFamily("楷体")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.label_3.setFont(font)
		self.label_3.setStyleSheet("background: rgb(255, 255, 255);")
		self.label_3.setObjectName("label_3")

		self.pushButton_10.setText("输出结果：")
		self.pushButton_11.setText("下一步")
		self.label_4.setText("TOPSIS模型分析")
		self.label_13.setText("权重:(%)")
		self.label_14.setText("权重:(%)")
		self.label_5.setText("权重:(%)")
		self.label_6.setText("权重:(%)")
		self.label_15.setText("权重:(%)")
		self.checkBox.setText("平台人数")
		self.checkBox_2.setText("男女比例")
		self.checkBox_4.setText("平台存在时间")
		self.checkBox_3.setText("有认证信息的达人数量")
		self.checkBox_5.setText("历史平均每日在线人数")
		self.label_18.setText("（根据相关文本分析，最终认定的产品赛道）")
		self.pushButton_8.setText("排名前十的美妆类品牌的平台关注人数")
		self.pushButton_9.setText("日均美妆类作品发布量")
		self.pushButton_7.setText("美妆类产品平台占有率")
		self.pushButton_6.setText("美妆类产品平台销售量")
		self.label_20.setText("(注：请选择上述你最倾向的指标，并设置权重，权重总和为100%)")
		self.label_17.setText("基础指标：")
		self.label_16.setText("(注：上述指标为不同赛道的个性化指标，后台进行数据处理，无需选择。)")
		self.label_19.setText("个性指标：")
		self.label_3.setText("美妆类产品")


class KOL_InitialSelectionTab(QWidget):
	def __init__(self):
		super().__init__()
		self.initGui()

	def initGui(self):
		self.tab = QtWidgets.QWidget()

class KOL_CompareTab(QWidget):
	def __init__(self):
		super().__init__()
		self.initGui()

	def initGui(self):
		self.tab = QtWidgets.QWidget()

class KOL_ForecastTab(QWidget):
	def __init__(self):
		super().__init__()
		self.initGui()

	def initGui(self):
		self.tab = QtWidgets.QWidget()

class FinalProposalTab(QWidget):
	def __init__(self):
		super().__init__()
		self.initGui()

	def initGui(self):
		self.tab = QtWidgets.QWidget()


def main():
	app = QApplication(sys.argv)
	mainWindow = MainWindow()
	mainWindow.show()
	sys.exit(app.exec_())

if __name__ == '__main__':
	main()